Observation new platform bulkupload
strandls/biodiv-observation pull request #86
Opened 2021-04-19 13:17 UTC by teamdraftbox

1. Observation bulk uploads api and implementation created, with ESstub changes with newPlatform support
2. Created DatasetId standalone Helper to execute on server start/start of Observation Context Listener to create standalone dataset record if not present.
3. Bulk Observation Mapper Helper created to add data from .xlxs file to observation database
4. DataTableDao created and DatasetDao add new method " FindByTitle"
5. ObservationBulkUploadThread created for batch processing of es-observation upload

2021-05-19 08:39 UTC, akrudra requested changes
Please finish this many changes first , and update the PR with the latest newPlatform branch.
we need to do several iternations

2021-05-20 17:56 UTC, teamdraftbox commented on src/main/java/com/strandls/observation/es/util/ReindexLatch.java
> +public class ReindexLatch extends Thread {
yes it is used in reindex util and reindexLatchManager for the reindexing api

2021-05-20 17:57 UTC, teamdraftbox commented on src/main/java/com/strandls/observation/es/util/Reindexing.java
> +public class Reindexing {
yes for the es reindexing api

2021-05-21 18:47 UTC, teamdraftbox commented on src/main/java/com/strandls/observation/pojo/ShowData.java
> +	private Long id;
yes it being used
https://github.com/strandls/biodiv-observation/blob/observation-bulk-upload/src/main/java/com/strandls/observation/es/util/ReindexLatch.java#L56

![Screenshot from 2021-05-22 00-16-53](https://user-images.githubusercontent.com/30981535/119184462-07dfd300-ba93-11eb-8176-bdc19d1d2627.png)

2021-05-21 18:47 UTC, teamdraftbox commented on src/main/java/com/strandls/observation/pojo/ShowData.java
> +	private Long id;
it is used in ur code , some POC reindex elastic,Pls look into it

2021-05-25 07:11 UTC, teamdraftbox commented on src/main/java/com/strandls/observation/es/util/ESUtilModule.java
> +		bind(Reindexing.class).in(Scopes.SINGLETON);
added https://github.com/strandls/biodiv-observation/blob/observation-newPlatform-bulkupload/src/main/java/com/strandls/observation/es/util/ESUtilModule.java

2021-05-26 10:32 UTC, akrudra requested changes
Read all the comments and look for the common errors in the rest of the files as well, like printstacktrace, use of static , using variable string instead of enum, inject method of jaxrs instead of google.. and change it through out the  code base

2021-05-26 10:32 UTC, akrudra commented on src/main/java/com/strandls/observation/service/Impl/DatasetConfigHelper.java
> +import com.google.inject.Inject;
jaxrs inject instead of google

2021-05-26 10:32 UTC, akrudra commented on src/main/java/com/strandls/observation/service/Impl/RecommendationServiceImpl.java
> +		TokenGenerator tokenGenerator = new TokenGenerator();
bind it to context listener and inject it

2021-05-26 10:32 UTC, akrudra commented on src/main/java/com/strandls/observation/util/FileParser.java
> +//	public static List<Map<String, Object>> parseFile(String filePath, BulkObservationDTO observationDTO) throws Exception {
this file ??? all code commented ?? if not being used delete it

2021-05-26 10:32 UTC, akrudra commented on src/main/webapp/WEB-INF/classes/hibernate.cfg.xml
> +		<mapping class="com.strandls.observation.pojo.DataTable"/>
remove the mapping from here, not required, initial we use to do that, but now its not required

2021-07-23 07:25 UTC, akrudra requested changes
Make the changes, remove the warnings, look for the issues you fixed during the sonar fix session, and format the code

2021-07-23 07:25 UTC, akrudra commented on src/main/java/com/strandls/observation/ApiConstants.java
> +	public static final String DATATABLEOBSERVATION = "dataTableObservation";
include a '/' in front of the path

2021-07-23 07:25 UTC, akrudra commented on src/main/java/com/strandls/observation/service/Impl/ObservationMapperHelper.java
> +	ObservationDAO observationDAO;
add private

2021-07-23 07:25 UTC, akrudra commented on src/main/java/com/strandls/observation/util/DataTableMappingField.java
> +	sGroup("sGroup"), checklistAnnotation("checklistAnnotation"), fromDate("fromDate"), geoPrivacy("geoPrivacy"),
capitalize the enum constants,  EX. sGroup("sGroup") to SGROUP("sGroup")

2021-07-23 07:25 UTC, akrudra commented on src/main/java/com/strandls/observation/util/DownloadLogHeader.java
> +	observationId("observationId"),
Capitalize the enum constants

2021-07-23 07:25 UTC, akrudra commented on src/main/java/com/strandls/observation/util/ObservationBulkUploadThread.java
> +		XSSFSheet sheet = workbook.getSheetAt(0);
include exception handling

2021-07-23 07:25 UTC, akrudra commented on src/main/java/com/strandls/observation/util/ObservationDeleteThread.java
> +		observationList.forEach(item -> {
include exception handling

2021-07-23 07:25 UTC, akrudra commented on src/main/java/com/strandls/observation/util/ObservationUtilModule.java
> +		bind(TokenGenerator.class).in(Scopes.SINGLETON);
include it directly inside context listerner class, we can save creation of a new class then

2021-07-27 16:46 UTC, merged